<?php

// autoload.php @generated by Composer

require_once ('vendor/composer/autoload_real.php');

//return ComposerAutoloaderInit9cffea4dc4f92ce52e18fea619dbdd4f::getLoader();

class Excel extends ComposerAutoloaderInit9cffea4dc4f92ce52e18fea619dbdd4f{
  public function __contruct(){
    ComposerAutoloaderInit9cffea4dc4f92ce52e18fea619dbdd4f::getLoader();
  }
}
